#!/bin/bash
#See you later hacker! [0]
#author @fesurocuts 790@holbertonschool.com fesusrocuts@gmail.com
#version 1.0.0.0
#date 08-06-2019
#run this code as root user
#description: the technique is attack use the lib curl and wget from Linux Ubuntu
#try hack poll #2 1/2
echo "get session #step1"
cat get-session | tr "\n" " " | sh
ls support/f1.level0.* | wc -l | awk '{if ($0>0) print "mv support/f1.level0.record support/f1.level0.record."$0}' | sh
