#!/bin/bash
#See you later hacker! [0]
#author @fesurocuts 790@holbertonschool.com fesusrocuts@gmail.com
#version 1.0.0.0
#date 08-06-2019
#run this code as root user
#description: the technique is attack use the lib curl and wget from Linux Ubuntu
#try hack poll #2 2/2
echo "get key #step2"
cat cookies.txt | grep HoldTheDoor | cut -f7 | awk '{print "--post-data \"id=790&key="$0"&holdthedoor=Submit+Query\""}' > post
cat prev-data | head -n 7 > post-data
cat post >> post-data
cat prev-data | tail -1 >> post-data
rm post
echo "push data for session #step3"
cat post-data | tr "\n" " " | sh
ls support/f2.level2.* | wc -l | awk '{if ($0>0) print "mv support/f2.level2.record support/f2.level2.record."$0}' | sh
