#!/bin/bash
#See you later hacker! [0]
#author @fesurocuts 790@holbertonschool.com fesusrocuts@gmail.com
#version 1.0.0.0
#date 08-06-2019
#run this code as root user
#description: the technique is attack use the lib curl and wget from Linux Ubuntu
#try hack poll #2 2/2
echo "autorun #step4"
for i in {1..97}
do
  ./pull
  ./push
  sleep 1
done
